name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: TerraformWorkingDirectory
    value: $(System.DefaultWorkingDirectory)/DevOps/terraform
  - name: AzureServiceConnection
    value: 'ExampleAzureServiceConnection'

stages:
  - stage: build
    displayName: Build
    jobs:
      - template: jobs/build-dotnet.yml@CICD
        parameters:
          BuildTargetPath: '**/ExampleAzureFunctions.csproj'
          DotNetVersion: '8.x'

  - stage: SetupInfrastructure
    displayName: Setup Infrastructure with Terraform
    dependsOn: build
    jobs:
      - template: jobs/setup-infrastructure.yml@CICD
        parameters:
          EnvironmentName: Test
          TerraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
          AzureServiceConnectionName: '${{ variables.AzureServiceConnection }}'
          AzureResourceGroupName: 'test-azure-function-rg'
          StorageAccountsName: 'testazurefunctionstorage'
          AzureContainerName: 'testazurefunctioncontainer'
          VarFilePath: 'DevOps/terraform/Test/test.tfvars'
          AzureRmKeyTFState: 'test.azure-function-infrastructure.tfstate'

  - stage: deploy
    displayName: Deploy Test
    dependsOn: SetupInfrastructure
    variables:
      - group: Test.ExampleAzureFunctions
    jobs:
      - template: jobs/deploy-azure-function.yml@CICD
        parameters:
          EnvironmentName: Test
          AzureSubscription: '${{ variables.AzureServiceConnection }}'
          AzureFunctionName: '${{ variables.AzureFunctionName }}'